id: P9E3C1884
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: bo
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    857348ee6ff34cc9ac9e23bb8f2b539a:
      title: Advice for Hor Özer
      parent: Advice
    855bca04eabd4d23b1092dda5dcb002e:
      title: Advice for Palseng
      parent: Advice
    7354de126fb54c1f850db8e0a4a7adc8:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    62f1caddf0b749cca102a4ad868a0f18:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    090bee28ad4a44fe81cec6ccece3a9ab:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    876a18b727c64079bf41789b30c21e21:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    9e75685e9345426995b59e56c1eb17ea:
      title: An Instruction on the Great Perfection
      parent: Advice
    979139994bfd4ca5a7d7ac2a153338c7:
      title: Brief Dzogchen Instruction
      parent: Advice
    99fe58ce8f9448adaf794e41b4fe6a3a:
      title: Direct Instruction
      parent: Advice
    d903047189094495bce46b80b439e778:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    57c7b7d0ee7c45c6935a73302a984728:
      title: Vajra Verses on the Natural State
      parent: Advice
    23ccc55e0d8441469e530713a68e86e8:
      title: Advice for a King
      parent: Advice
    e4378fcc96b648f694ff68a8ac5abbf6:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    db3c400c915845db95fe75150c34c7c2:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    604ca17cc1d941c7b3807d4007689bae:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    c3150e2e56f742b69bc3353578033d96:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    8868aadddeb84616a6d1cf9397d58a4f:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    c606aee5e7694e8c82025deddec90175:
      title: A Liberating Reminder
      parent: Advice
    d866c983018740d4b1f1adc512350193:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    45acaa404bdb4845ba2952acf8b31d54:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    e927cde48b884615a29d335dc9adc6b2:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    60b718810b384af6a0ac9e72090fd89d:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    698c03ce45ac4fd4aaa1de63d9682dba:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    0d554f33beae484a879c9f2c8aef2503:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    464409d778aa4f97b2ed65007246bb42:
      title: The Essence of Mind
      parent: Advice
    ac90e2e38914401bbbfecc3202603bfa:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    3b2781b331c941aba3e111814e828b84:
      title: The Key Points of Trekchö
      parent: Advice
    bab994c60fdd4f55a28b8ab27dbd6003:
      title: The Nature of Mind
      parent: Advice
    8f6399ff771d490ba8be10a9b0c3df0b:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    42f0c176caa642739d1b70bbaa374f6e:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    ffd2c0fda37f4637b75be3960be66b17:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    9a801ee62b4c44ef960a668fbb899452:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    b7c67136481647b3b9ba66cbd718e8d5:
      title: The Five Wisdoms
      parent: Advice
    bdfa1d09f81a4e59bee76ee9d92b335c:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    68f41cbe999746d19a9ec24e2f4927f6:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    596527d25c344bb980eb44be75ea3e8e:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    b56b1f6e3f4d4a109925c392a478ea86:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    1ba31ba1f7d84d339fea1c162a0cb3d4:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    58188646255d497e8fd7c8a0029f8945:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    7581187f22c7499baca29c8f965526dc:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    5ad425e455df46c7a405ca1d64d0d398:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    9387f43e542144d08e92b0d4399308ac:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    e80a405f04ca4dce83f806dad0d6a044:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    2e3a78f73d5749658e74ed470dd18315:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    7ebb5d54838b4657831ad9720b82c27e:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    e281c1572d954cf1b9adfccb10af50fb:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    941f9754a4bf4779b8bf78a2cf840466:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    604deaa1cd2c4c1ea01365c53282f233:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    ba76a837eba14d9d8c4a014babebc181:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    b8d3ca00eb2242809480806a42482017:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    4d508663e4b04645a4e2d7a7dfb950ab:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    feb6fe14746542daaed705b4ea8b8488:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    598f516e9cc740da931b9e98714411b5:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    5c1422088aa34f6397929d190f4e67ee:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    19ea777a828f4f9d8fda20de8546738e:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    5e88574a01384c3eaa9bb07cd3917db5:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    e21fa46f6cf94564bdd0ca87cc7742dc:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    b83b1ebebaa34880bf007b3bd0782377:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    450ac42b61ca4c269b150dfc0cae0582:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    8b2b9743250e4cff82b685ff3fcc342c:
      title: The Song of the Vajra
      parent: Songs
    8f6abb9f4b4f415ea76a7a521460996c:
      title: A Song in Six Verses
      parent: Songs
    e6160f192f364a93895c23ff6b77e272:
      title: Song of Experiential Certainty
      parent: Songs
    1f8a1de32e0a40279a8ef4d6a62baee9:
      title: Spontaneously Written Song of Experience
      parent: Songs
    0bb9e8a289de49c6b3c93306eb81a215:
      title: In This Pure Awareness
      parent: Songs
    08659d062feb4142ad6cd14789241d46:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    5be06b2f6e6842a1965dac8903a69b13:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    1410107b1f3844c4a269ef4e2de0fdac:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:32.004306'
last_modified_at: '2022-03-01T03:36:32.004309'
